* operating system
** linux
*** CentOS 7
**** 学习资料
***** 鸟哥的linux私房菜
****** 服务器篇
******* 11.1 远程连接服务器
******** 11.2.4 客户端连接程序-Windows用户
与Linux不同的是，预设的Windows并没有ssh的客户端程序，因此所有的程序都得要下载其他第三方软
才行。常见的软件主要有putty，psftp及filezilla等。下面就让我们来谈谈这几个软件吧。
********* 直接连接的putty
在Linux下面想要连接SSH服务器，可以直接利用ssh这个命令，在Windows操作系统下面就得要使用put
ty这个软件了，软件下载地址请参考：
+ putty官方网站：[[http://www.chiark.greenend.org.uk/~sgtatham/putty/]]
在putty的官方网站上有很多的软件可以使用，包括putty/pscp/psftp等等。他们分别对应了ssh/scp
/sftp这三个命令。

[[http://linux.vbird.org][鸟站首页]]
****** linux基础文件
底下的几篇文章是学习Linux的基础文件，这些文件是基础中的基础，如果您能将其中的文件都看完并且
消化过，那么未来在管理Linux主机以及架设网站方面，就能够达到【事关功倍】的成效，请不要忽略这
部份了！否则，再怎么讨论都是枉然的啦！^_^。因为Linux的资料非常的多，每份资料彼此的相关性都
很强，要单独的一项一项讲解并不容易，所以底下的文件该怎么看呢？建议先按照顺序将内容大致浏览过
一次，看不懂的地方可以先略过不要紧。全部看完之后，再从头开始【仔细】的实际操作一遍，那应该就
能够进入Linux的世界~
******* 基础文件汇整表
******** 第一部分：Linux的规划与安装
******** 第二部分：Linux档案、目录与磁盘格式
******** 第三部分：学习Shell与Shell Scripts
******** 第四部分：Linux使用者管理
******** 第五部分：Linux系统管理员
******** 第六部分：其他备份文章
******* 第零章、计算机概论
由过去的经验当中，鸟哥发现因为兴趣或生活所逼而必须接触Linux的朋友，很多可能并非资讯相关科系
出身，因此对于电脑软/硬件方面的概念不熟。然而操作系统这种东东跟硬件有相当程度的关联性，所以，
如果不了解一下计算机概论，要很快的了解Linux的概念是有点难度的。因此，鸟哥就自作聪明的新增一
个小章节来谈谈计概！因为鸟哥也不是信息相关学科出身，所以，写的不好的地方请大家多多指教啊！
^_^
******** 0.1 电脑：辅助人脑的好工具
********* 0.1.1 电脑硬件的五大单元
********* 0.1.2 一切设计的起点：CPU的架构，RISC与ARM，CISC与x86
********* 0.1.3 其他单元的设备
********* 0.1.4 运作流程
********* 0.1.5 电脑用途的分类
********* 0.1.6 电脑上面常用的计算单位（容量、速度等）
******** 0.2 个人电脑架构与相关设备元件
********* 0.2.1 执行脑袋运算与判断的CPU：CPU的工作时脉，32位与64位，CPU等级，超线程
********* 0.2.2 内存：多通道，DRAM与SRAM,ROM
********* 0.2.3 显卡：PCIe规格
********* 0.2.4 硬盘与储存设备：物理组成，磁盘与扇区，传输界面（SATA,SAS,USB...），SDD，购买与运转
********* 0.2.5 扩充卡与界面
********* 0.2.6 主板
********* 0.2.7 电源
********* 0.2.8 选购须知
******** 0.3 资料表示方式
********* 0.3.1 数字系统
********* 0.3.2 文字编码系统
******** 0.4 软件程序运行
**** 安装配置
***** 1. 最小化安装
***** TODO 2. 配置网络
参考[[http://blog.csdn.net/readiay/article/details/45338709][VMware虚拟机设置centos固定ip地址]]
****** 1. 修改VMware的虚拟网络编辑器
1. 打开VMware虚拟网络编辑器（编辑->虚拟网络编辑器）
2. 选中NAT模式，修改一些配置就行了.[[][图2]]
3. 例如我想设置我的虚拟机固定ip是192.168.133.255
   那么子网ip就设置成192.168.133.0
   子网掩码保持不变：255.255.255.0
   使用本地DHCP这个不要选，这个是动态给虚拟机分配ip的，我们不需要
4. 点击NAT设置[[][图1]]
5. 这个网关就是我们虚拟机中使用的网关，好像这个虚拟机中的网关都是类似xxx.xxx.xxx.2这种以2结尾的，保存退出。
****** 2. centos中设置网络
涉及文件列表：
/etc/sysconfig/network-scripts/ifcfg-eth0（网卡）
/etc/sysconfig/network（主机名）
/etc/resolv.conf（DNS）
1. /etc/sysconfig/network-scripts/ifcfg-eth0
[[][图3]]
也可以在ifcfg-eth0这个文件中加上DNS1=192.168.129.2来实现DNS设置（如果这样的话下面第3步就可以省略了）
2. /etc/sysconfig/network
[[][图4]]
这里文件中设置网关的GATEWAY。就是上面提到的那个NAT中的网关
3. /etc/resolv.conf
[[][图5]]
这个文件中添加一个nameserver这个用来解析域名的。
你可以写8.8.8.8，我这里写的是网关地址。
如果这个不设置，那么ping www.baidu.com
就可能找不到www.baidu.com地址。
如果你的电脑每次重启以后，这个文件中的内容被刷新了，那就百度吧。
我使用的centos是mini版的，什么都没有，所以不会被刷新。
4. 设置完这些以后，就重启一下，然后运行命令ifconfig。出现两个就说明OK了。
[[][图6]]

***** 3. 安装配置httpd
***** 4. 安装配置php
***** 5. 用ssh代替ftp
****** 1. 安装配置vsftpd
    DEADLINE: <2017-02-28 周二>
[[http://blog.csdn.net/wave_1102/article/details/50651433][ftp服务器搭建]]
****** 2. 安装配置putty
******* TODO 1. putty学习
******* TODO 2. pscp,psftp,plink学习
***** 6. 安装配置postgresql
      [[http://blog.csdn.net/wn_hello/article/details/52289390][postgresql安装与配置介绍]]
***** 7. iptables
***** 8. selinux
***** 9. 数据备份
**** shell
***** bash
**** editor
***** emacs
****** org-mode
***** emacs是什么
emacs是一个高效的文本编辑器。
****** 下载
emacs官网地址：http://www.gnu.org/software/emacs/
****** 安装
******* windows下安装
解压后运行bin目录下的addpm.exe
******* linux下安装
****** 配置
******* 常规配置
******* 插件配置
******** evil配置
******** magit配置
******** w3m配置
******** 
****** 安装httpd
     yum install httpd
     chkconfig httpd on
     firewall --zone=public --add-port=80/tcp --permanent
     systemctl start httpd.service
****** 安装php,php-pgsql
     yum install php
     yum install php-pgsql
****** 安装postgresql-server
     yum install postgresql-server
     postgresql-setup initdb
     chkconfig postgresql on
     systemctl start postgresql.service
*** deploy
**** install centos7
**** configure network
***** 配置虚拟机软件的网络
***** 配置虚拟主机的网络
   vi /etc/sysconfig/network-scripts/ifcfg-xxx 注：配置网卡，xxx是网卡名
   BOOTPROTO=static
   DNS1=192.168.69.2
   IPADDR=192.168.69.9
   NETMASK=255.255.255.0
   ONBOOT=yes 

   vi /etc/sysconfig/network	注：配置主机
   NETWORKING=yes
   HOSTNAME=capp
   GATEWAY=192.168.69.2
**** configure software source
     从[[http://mirrors.163.com ][网易开源镜像站]]下载CentOS-Base-163.repo,putty到虚拟主机。
   mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.backup
   yum clean all
   yum makecache
** windows
*** putty/psftp
* programming language
** c
** cpp
** css
** html
** php
** sql
